### ISSUE TITLE
Refactor data structure (again)

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-github-provider#12]
After reviewing  https://github.com/senecajs/seneca-github-provider/pull/10/files it occurs to me that we need to make another refactoring. That is OK! This is the way code improves - you discover a good solution and converge towards it.

Do not be afraid to delete code: https://burritalks.io/talks/greg-young-the-art-of-destroying-software/

Here is the issue: modifications occur in two places per command:
* before data is sent to the REST API - we have a `query`, and possibly an `entity`
* after data is returned from REST API - we have a `response`

We need to separate these in the data structure that defines an entity, so that it is clear what will happen. Thus move to this structure:

```
  actions: {
    load: {
      action: 'get',
      after: [
        { on:'outent' field: 'id', set: { query: 'id' } },
        { on:'outent', field: 'github_native_id', set: { response: 'id' } }
      ],
    },
    save: {
      before: [
        { on:'request', field: 'id', set: { inent: 'github_native_id' } },
      ],          
      after: [
        { on:'outent', field: 'id', set: { inent: 'id' } },
        { on:'outent', field: 'github_native_id', set: { response: 'id' } }
      ],          
    },
    ...
```

The before and after arrays are a set of actions, both are optional. Each action has the form:
```
type Action = {
  on: '<TARGET>'
  field: '<FIELDNAME>',
  <CMD0>: <SPEC0>,
  <CMD1>: <SPEC1>,
  ...
}
```

The target can be:
* `inent`: the input entity (`msg.ent`)
* `outent`: the output entity (returned by `load$` or `save$`)
* `query`: input query (`msg.q`)
* `request`: the JSON object sent as the request to the REST API
* `response`: the JSON object returned by the REST API

At the moment we only define the command `set` - we can add more later as needed.

`set` works as follows:
```
{
  on: <TARGET>,
  field: <TARGETFIELD>
  set: { <SOURCE>: '<SOURCEFIELD>' }
}
```

means: ` TARGET[TARGETFIELD] = SOURCE[SOURCEFIELD]`

of course, you will need to write code to set TARGET and SOURCE.

Implement `set` as a function with signature:

`set(action: Action, context: Context)`

and define:

```
type Context = {
  inent?: any
  outent?: any
  query?: any
  request?: any
  response?: any
}
``` 

Thus to process actions, such as `set`, you set up the Context object first.

Another point: this is probably going to be needed in other providers, many even Eventbrite. Thus is is worth investing time in creating a general solution. 

Make this a separate utility file, and include write unit tests for it.

**Comment by rjrodger** [comment]
Oh yes - `github_native_id` - let's use this universally instead of `repo_id` etc, then it will always be the same

**Comment by rjrodger** [comment]
the term "Action" is ambiguous here - it is used both for load|save, and for the before|after operations
perhaps use "Cmd" for load|save, as this is what seneca-entity uses
and Task for before|after items

**Comment by guhmerces** [comment]
> Oh yes - `github_native_id` - let's use this universally instead of `repo_id` etc, then it will always be the same

Richard, I included this repo_id in almost every entity to avoiding passing it every time we need to load/save them. By github_native_id you mean the ID of the original object returned from the api? or the repo_id (owner/repo) itself in each entity ?

**Comment by guhmerces** [comment]
> the term "Action" is ambiguous here - it is used both for load|save, and for the before|after operations perhaps use "Cmd" for load|save, as this is what seneca-entity uses and Task for before|after items

Richard, after calling the "modify" objects by Tasks, there is no longer any conflict related to naming. You still think we should get rid of the Actions terms and replace them by Cmd term?
