### ISSUE TITLE
refactor to make iteration over ents the primary way that messages are added

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-github-provider#15]
https://github.com/senecajs/seneca-github-provider/blob/main/src/github-provider.ts#L36

the for loop should iterate over the `ents`
there is no need for the switch. do this instead:

```
for( const ent of ents ) {
  seneca.message(ent.pattern, make_load(ent)) 
  seneca.message(ent.pattern, make_save(ent))
}
``` 

rename prepare_actions to prepare_ents and add the pattern to the ent description in that function

in general, avoid conditions by building the data structure to avoid them

**Comment by guhmerces** [comment]
@rjrodger I linked a pr to this issue
