### ISSUE TITLE
the key should also be the name of the entity, so what I do in this case is a post-processing step to enhance the data structure and stay DRY:

### ISSUE THREAD

**Issue by guhmerces** [senecajs/seneca-github-provider#5]
the key should also be the name of the entity, so what I do in this case is a post-processing step to enhance the data structure and stay DRY:
```
for([name,entry] of Object.entries(entities_map) {
  entry.name = name
}
```

_Originally posted by @rjrodger in https://github.com/senecajs/seneca-github-provider/pull/4#discussion_r783142742_

**Comment by rjrodger** [comment]
perhaps this can be done here: https://github.com/senecajs/seneca-github-provider/blob/main/src/github-provider.ts#L32
`data.name = ent_name`

**Comment by rjrodger** [comment]
@guhmerces is this resolved?

**Comment by guhmerces** [comment]
@rjrodger , not yet, I'll put this and the last missing one in the next PR

**Comment by guhmerces** [comment]
@rjrodger  I linked a PR to this issue
