### ISSUE TITLE
separate resolving the entity actions, and defining the actions

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-github-provider#7]
at the moment `add_actions` is doing too much work - separate this into:

`prepareActions` - a function to prepare the entity definitions
`make<Action>` - functions to create the action functions

and a loop over the entities to define the actions:

```
let actions = prepareActions(entities)

for(action of actions) {
  seneca
    .message( action.pattern, makeLoad(action))
    .message( action.pattern, makeSave(action))
}
```

It is better to define messages only at the top level so it is easier to see what messages a plugin defines.

The make<Action> functions are your logic in https://github.com/senecajs/seneca-github-provider/blob/main/src/cmd-handlers.ts

**Comment by guhmerces** [comment]
@rjrodger  Hi Richard, I just linked a PR to this issue.

I wasn't able to make the task as per in your example in this issue description. The barrier I found is that: as each pattern is related to a single action, I should call `seneca.message(pattern, make<action>(action))` just once for each pattern. So I included a switch block.
