### ISSUE TITLE
avoid ad hoc mini language

### ISSUE THREAD

**Issue by rjrodger** [senecajs/seneca-github-provider#8]
let's just use normal JSON to represent out entity definitions:
https://github.com/senecajs/seneca-github-provider/blob/main/src/cmd-handlers.ts#L18

https://github.com/senecajs/seneca-github-provider/blob/main/src/entities.ts#L15
perhaps:
```
includes: [ { field:string, rename?:string }, ...]
```

also perhaps `includes` should be `modify` as we may wish to expand this future

**Comment by guhmerces** [comment]
Hey Richard. I linked a PR related to this issue.
